# Generated by Django 3.2.6 on 2021-08-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlgenerator',
            old_name='text',
            new_name='body',
        ),
    ]
